# Site settings
title: Tyler Tretsven
email: tyler.tretsven@gmail.com
description: "Portfolio"
baseurl: ""
url: "http://localhost"
twitter_username: tylertretsven
github_username:  tylertretsven

# Build settings
markdown: kramdown
permalink: pretty
